name: Scheduled Playwright Tests

# Run tests on a schedule (daily at 2 AM UTC)
on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  scheduled-tests:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run full test suite
      run: npx playwright test --reporter=html,json
      env:
        CI: true
    
    - name: Upload comprehensive test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: scheduled-test-report-${{ github.run_number }}
        path: |
          playwright-report/
          test-results/
          results.json
          results.xml
        retention-days: 7
    
    - name: Create test summary
      if: always()
      run: |
        echo "## 📊 Scheduled Test Results" >> $GITHUB_STEP_SUMMARY
        echo "**Test Run:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "**Run Number:** ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
        
        if [ -f "results.json" ]; then
          echo "**Results available in artifacts**" >> $GITHUB_STEP_SUMMARY
        fi
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "🚨 Scheduled tests failed!"
        echo "This may indicate issues with the AZ Blue website."
        # You can add Slack/Teams/Email notifications here
